### ISSUE TITLE
Bonjour AndrewBot

### ISSUE THREAD

**Issue by patrick-andrew-jain-taylor** [Trinitui/AndrewBot#25]
Based on a poem by Jim Joe Kelly.

> I've been walking down these streets for years. They all know my name. But I can't say that I know theirs. What can I say? Sweet Paris. The smell of baguettes, flowers, fresh meat in the air. This is a town full of beautiful people all around you. Oui, oui. Magnifique. I'm Diamond Jim. This is my home. My people. But there's only one that has my attention.

Request: Saying “Bonjour AndrewBot” should have AndrewBot respond as follows:

* Bonjour
* Oui, oui.
* Magnifique
* What do I have to do to get you to finally go out with me?

**Comment by Trinitui** [comment]
This has been added.
